### ISSUE TITLE
Node version 10 breaking change causing false positive connection end msg

### ISSUE THREAD

**Issue by glebec** [glebec/volleyball#28]
Getting `connection closed before res end/flush` on every single request in Node v10+.

**Comment by ronag** [comment]
There was a bug related to this in 10.2.0. But it should have been fixed in 10.2.1. What version of node are you experiencing this on?

**Comment by glebec** [comment]
@ronag 10.3.

**Comment by ronag** [comment]
Yea, you need to remove the close listener on 'finish'. Alternatively you could use `req.on('aborted')` to achieve what I believe you are looking for.

**Comment by glebec** [comment]
Yep, I have been looking at the Node changelog. As of this post, the [docs](https://nodejs.org/api/http.html#http_event_close_1) still claim that `close` "indicates that the underlying connection was terminated before `response.end()` was called or able to flush" – that doesn't appear to be 100% accurate anymore. Removing the `close` listener upon `finish` sounds promising, I'll try it later. Thanks, —G.

**Comment by ronag** [comment]
https://github.com/nodejs/node/pull/21047
